/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as StatementRouteImport } from './routes/statement'
import { Route as PinLoginRouteImport } from './routes/pin-login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FingerprintLoginRouteImport } from './routes/fingerprint-login'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementRoute = StatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => rootRouteImport,
} as any)
const PinLoginRoute = PinLoginRouteImport.update({
  id: '/pin-login',
  path: '/pin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FingerprintLoginRoute = FingerprintLoginRouteImport.update({
  id: '/fingerprint-login',
  path: '/fingerprint-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/fingerprint-login': typeof FingerprintLoginRoute
  '/home': typeof HomeRoute
  '/pin-login': typeof PinLoginRoute
  '/statement': typeof StatementRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/fingerprint-login': typeof FingerprintLoginRoute
  '/home': typeof HomeRoute
  '/pin-login': typeof PinLoginRoute
  '/statement': typeof StatementRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/fingerprint-login': typeof FingerprintLoginRoute
  '/home': typeof HomeRoute
  '/pin-login': typeof PinLoginRoute
  '/statement': typeof StatementRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance'
    | '/dashboard'
    | '/deposit'
    | '/fingerprint-login'
    | '/home'
    | '/pin-login'
    | '/statement'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balance'
    | '/dashboard'
    | '/deposit'
    | '/fingerprint-login'
    | '/home'
    | '/pin-login'
    | '/statement'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/balance'
    | '/dashboard'
    | '/deposit'
    | '/fingerprint-login'
    | '/home'
    | '/pin-login'
    | '/statement'
    | '/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalanceRoute: typeof BalanceRoute
  DashboardRoute: typeof DashboardRoute
  DepositRoute: typeof DepositRoute
  FingerprintLoginRoute: typeof FingerprintLoginRoute
  HomeRoute: typeof HomeRoute
  PinLoginRoute: typeof PinLoginRoute
  StatementRoute: typeof StatementRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statement': {
      id: '/statement'
      path: '/statement'
      fullPath: '/statement'
      preLoaderRoute: typeof StatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin-login': {
      id: '/pin-login'
      path: '/pin-login'
      fullPath: '/pin-login'
      preLoaderRoute: typeof PinLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fingerprint-login': {
      id: '/fingerprint-login'
      path: '/fingerprint-login'
      fullPath: '/fingerprint-login'
      preLoaderRoute: typeof FingerprintLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalanceRoute: BalanceRoute,
  DashboardRoute: DashboardRoute,
  DepositRoute: DepositRoute,
  FingerprintLoginRoute: FingerprintLoginRoute,
  HomeRoute: HomeRoute,
  PinLoginRoute: PinLoginRoute,
  StatementRoute: StatementRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
